### ISSUE TITLE
Can't run buildout after creating new project

### ISSUE THREAD

**Issue by kuzmich** [twillis/pyramid_appengine#30]
Error:
```
$ bin/buildout 
Getting distribution for 'setuptools==1.1.7'.
Got setuptools 1.1.7.
The constraint, 1.1.7, is not consistent with the requirement, 'setuptools>=8.0'.
While:
  Installing.
  Checking for upgrades.
Error: Bad constraint 1.1.7 setuptools>=8.0
```
Steps performed:
```
$ cd /tmp/
$ mkdir gae_pyramid
$ cd gae_pyramid/
$ virtualenv -p /usr/bin/python2.7 --no-site-packages --distribute venv
$ source venv/bin/activate
$ pip install pyramid_appengine
$ pcreate -t appengine_starter newproject
$ cd newproject
$ python bootstrap.py
$ bin/buildout
```
OS: Kubuntu 14.04
Python: 2.7.6
Pip: 6.0.8
Virtualenv: 12.0.7
Setuptools: 12.0.5

**Comment by twillis** [comment]
try changing the setuptools version in the generated versions.cfg for your project. and let me know how that goes.

**Comment by kuzmich** [comment]
Tried to change setuptools version to `12.0.5` (and 'ae-sdk-version' in buildout.cfg to `1.9.17` since it can't download `1.9.11`), I got following error:
```
Traceback (most recent call last):
  File "/tmp/gae_pyramid/newproject/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/tmp/gae_pyramid/newproject/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 626, in install
    installed_files = self[part]._call(recipe.install)
  File "/tmp/gae_pyramid/newproject/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1370, in _call
    return f()
  File "/tmp/gae_pyramid/newproject/eggs/rod.recipe.appengine-2.0.6-py2.7.egg/rod/recipe/appengine/__init__.py", line 380, in install
    self.copy_packages(ws, temp_dir)
  File "/tmp/gae_pyramid/newproject/eggs/rod.recipe.appengine-2.0.6-py2.7.egg/rod/recipe/appengine/__init__.py", line 283, in copy_packages
    self.write_pkg_resources(ws, lib)
  File "/tmp/gae_pyramid/newproject/eggs/rod.recipe.appengine-2.0.6-py2.7.egg/rod/recipe/appengine/__init__.py", line 257, in write_pkg_resources
    assert len(setuptools_eggs) == 1, "setuptools not found"
AssertionError: setuptools not found
```

**Comment by twillis** [comment]
I cut a new release that has an updated bootstrap.py which seems to work with the newer setuptools shenannigans. also bumped the sdk version. You should be good to go.

**Comment by kuzmich** [comment]
I'm getting the same `AssertionError: setuptools not found` error in rod.recipe.

**Comment by twillis** [comment]
you need to generate a new project. this library only generates project skeletons, after a project skeleton is generated, it's all buildout and appengine sdk

**Comment by kuzmich** [comment]
Yes, I made all the steps from the begining.

**Comment by twillis** [comment]
I can't reproduce this on the new version I cut for you yesterday. 

``bash
~/$ mkdir t
~/$ cd t
~/t$ virtualenv -p /usr/local/bin/python2.7 ./
~/t$ ./bin/pip install pyramid_appengine
~/t$ ./bin/pcreate -t appengine_starter testproject
~/t/testproject$ cd testproject/
~/t/testproject$ ../bin/python bootstrap.py 
~/t/testproject$ ./bin/buildout 
~/t/testproject$ ./bin/supervisord -n
``

![screen shot 2015-02-10 at 8 03 58 am](https://cloud.githubusercontent.com/assets/183699/6127651/799e858e-b0fb-11e4-91a2-e3dcf326630d.png)


maybe paste the contents of your bootstrap.py

**Comment by kuzmich** [comment]
It's the same bootstrap.py file as in your package. Looks like it's the same issue as #26 and actually issue of the rod.recipe.appengine.
